#+STARTUP: showeverything

#+begin_quote
Art is pain.

Life is suffering.
#+end_quote

#+begin_quote
Iron sharpens iron.
#+end_quote

#+begin_quote
It is possible to commit no mistakes and still lose. That is not
weakness. That is life.

-- Jean Luc Picard
#+end_quote

#+begin_quote
Everybody has a plan until they get punched in the mouth.

-- Mike Tyson
#+end_quote

#+begin_quote
A human being should be able to change a diaper, plan an invasion,
butcher a hog, conn a ship, design a building, write a sonnet, balance
accounts, build a wall, set a bone, comfort the dying, take orders,
give orders, cooperate, act alone, solve equations, analyse a new
problem, pitch manure, program a computer, cook a tasty meal, fight
efficiently, die gallantly. Specialization is for insects.

-- Robert Heinlein, Time Enough for Love
#+end_quote

#+begin_quote
We don't rise to the level of our expectations, we fall to the level
of our training.

-- Archilochos
#+end_quote

#+begin_quote
You can't improve what you don't measure.
#+end_quote

#+begin_quote
I sing the body electric -- Walt Whitman
#+end_quote

- je ne sais quoi :: An indefinable quality that makes something
     distinctive or attractive ([[https://en.wiktionary.org/wiki/je_ne_sais_quoi][Wiktionary]]).

* Notices
Attempt to derive a possible answer to a question first, before
comparing it against the actual answer you receive.

* Goal Setting
When setting goals, consider making it:
- Specific
- Measurable
- Assignable
- Realistic
- Time-bound

* Hashing Bitwarden passwords

aes-encrypted V 1.3-OCB-B-4-4-M
gnGGTMQS6T1E1P0S56Syu1UHmMyhX77WxyH9XKhDI4P41DlMfSkt7pv3NhaGn8z/WLlU61Wiwk8f
9KZvCcdw9ezeoFrRkBbzJY9VAPVs3dlMfZw3jYdzA968dEWgUUVSfh8xONrd
