(require 'config-helpers)
(require 'config-evil)
(require 'config-evil-helpers)
(require 'config-git)
(require 'config-colors)
(require 'config-completions)
(require 'config-emacs)
(require 'config-org)
(require 'config-org-capture)
(require 'config-org-capture-templates)

(require 'config-japanese)
(require 'config-anki)

(provide 'config)
