;;; Automatically generated by ‘recentf’ on Mon Apr  2 14:36:01 2018.

(setq recentf-list
      '(
        "c:/Users/pangt.ADS/AppData/Roaming/.emacs.d/init.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
